version: "3.8"

services:
  zepplin:
    build:
      context: /data/projects/zepplin
      dockerfile: Dockerfile
    container_name: zepplin-registry
    restart: unless-stopped
    network_mode: host
    volumes:
      - zepplin_data:/app/data
      - zepplin_packages:/app/packages
      - /data/projects/zepplin/backups:/app/backups:ro
    environment:
      - ZEPPLIN_DATA_DIR=/app/data
      - ZEPPLIN_PORT=8080
      - ZEPPLIN_DOMAIN=${ZEPPLIN_DOMAIN:-zig.cktech.org}
      - ZEPPLIN_REGISTRY_NAME=${ZEPPLIN_REGISTRY_NAME:-CKTech Zig Registry}
      - ZEPPLIN_LOG_LEVEL=${ZEPPLIN_LOG_LEVEL:-info}
      - ZEPPLIN_MAX_PACKAGE_SIZE=${ZEPPLIN_MAX_PACKAGE_SIZE:-50MB}
      - ZEPPLIN_ENABLE_WASM=${ZEPPLIN_ENABLE_WASM:-true}

volumes:
  zepplin_data:
    driver: local
    name: zepplin_data
  zepplin_packages:
    driver: local
    name: zepplin_packages
