version: '3.8'

services:
  zepplin:
    build: .
    ports:
      - "${ZEPPLIN_PORT:-8080}:8080"
    volumes:
      - zepplin-data:/app/data
    environment:
      - ZIG_ENV=production
      - ZEPPLIN_DATA_DIR=/app/data
      - ZEPPLIN_LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - zepplin-network

volumes:
  zepplin-data:
    driver: local
    name: zepplin-data

networks:
  zepplin-network:
    driver: bridge
    name: zepplin-network
