services:
  zepplin-registry:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: "0.5.1"
    container_name: zepplin-registry
    restart: unless-stopped
    ports:
      - "8888:8888"  # Bind to all interfaces for external access
    volumes:
      - zepplin_data:/app/data
      - zepplin_packages:/app/packages
      - ./web:/app/web:ro
      - ./assets:/app/assets:ro
      - ./backups:/app/backups
      - ./logs:/app/logs
    environment:
      - ZEPPLIN_VERSION=0.5.1
      - ZEPPLIN_PORT=8888
      - ZEPPLIN_BIND_ADDRESS=0.0.0.0
      - ZEPPLIN_SECRET_KEY=${ZEPPLIN_SECRET_KEY:-insecure-default-change-me}
      - ZEPPLIN_DB_PATH=/app/data/zepplin.db
      - ZEPPLIN_STORAGE_PATH=/app/data
      - ZEPPLIN_DOMAIN=${ZEPPLIN_DOMAIN:-zig.cktech.org}
      - ZEPPLIN_REGISTRY_NAME=${ZEPPLIN_REGISTRY_NAME:-Zepplin Registry}
      - ZEPPLIN_LOG_LEVEL=${ZEPPLIN_LOG_LEVEL:-info}
      - ZEPPLIN_ZIGISTRY_URL=${ZEPPLIN_ZIGISTRY_URL:-}
      
      # OAuth/OIDC Configuration for production
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - REDIRECT_BASE_URL=${REDIRECT_BASE_URL:-https://zig.cktech.org}
      - JWT_SECRET=${JWT_SECRET:-change-me-in-production}
      
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.cktech.service=zepplin-registry"
      - "com.cktech.version=0.5.1"
      - "com.cktech.description=Lightning-fast Zig Package Registry with OAuth"

volumes:
  zepplin_data:
    driver: local
    name: zepplin_data
  zepplin_packages:
    driver: local
    name: zepplin_packages

networks:
  default:
    external: true
    name: nginx-net