services:
  zepplin-registry:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: "0.4.0"
    container_name: zepplin-registry
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - zepplin_data:/app/data
      - zepplin_packages:/app/packages
      - ./web:/app/web:ro
      - ./assets:/app/assets:ro
      - ./backups:/app/backups
      - ./logs:/app/logs
    environment:
      - ZEPPLIN_VERSION=0.4.0
      - ZEPPLIN_DATA_DIR=/app/data
      - ZEPPLIN_PORT=8080
      - ZEPPLIN_DOMAIN=${ZEPPLIN_DOMAIN:-localhost}
      - ZEPPLIN_REGISTRY_NAME=${ZEPPLIN_REGISTRY_NAME:-Zepplin Registry}
      - ZEPPLIN_LOG_LEVEL=${ZEPPLIN_LOG_LEVEL:-info}
      - ZEPPLIN_MAX_PACKAGE_SIZE=${ZEPPLIN_MAX_PACKAGE_SIZE:-50MB}
      - ZEPPLIN_ENABLE_WASM=true
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.cktech.service=zepplin-registry"
      - "com.cktech.version=0.4.0"
      - "com.cktech.description=Lightning-fast Zig Package Registry"

volumes:
  zepplin_data:
    driver: local
    name: zepplin_data
  zepplin_packages:
    driver: local
    name: zepplin_packages