const std = @import("std");
const commands = @import("commands.zig");
const types = @import("../common/types.zig");
const zigistry = @import("../zigistry/client.zig");

pub fn executeCommand(allocator: std.mem.Allocator, io: std.Io, args: commands.CliArgs) !void {
    switch (args.command) {
        .init => try initProject(allocator, io),
        .add => try addPackage(allocator, io, args.package_name orelse return commands.CliError.MissingArgument, args.version),
        .update => try updatePackages(allocator, io),
        .build => try buildProject(allocator, io),
        .publish => try publishPackage(allocator, io),
        .login => try loginToRegistry(allocator, io, args.registry_url),
        .discover => try discoverPackages(allocator, io, args.package_name),
        .browse => try browsePackages(allocator, io, args.category),
        .trending => try showTrending(allocator, io, args.category),
        .help => commands.printHelp(),
    }
}

fn initProject(_: std.mem.Allocator, io: std.Io) !void {
    std.debug.print("🚀 Initializing new Zepplin project...\n", .{});

    // Create zepplin.toml
    const toml_content =
        \\[package]
        \\name = "zepplin"
        \\version = "0.1.0"
        \\description = "Zepplin self hosted zig packages & libraries!"
        \\author = "Christopher Kelley"
        \\license = "MIT"
        \\[dependencies]
        \\# Add your dependencies here
        \\# example = "1.0.0"
        \\
        \\[registries]
        \\default = "https://registry.zepplin.dev"
        \\
    ;

    const file = std.Io.Dir.cwd().createFile(io, "zepplin.toml", .{}) catch |err| switch (err) {
        error.PathAlreadyExists => {
            std.debug.print("❌ zepplin.toml already exists\n", .{});
            return;
        },
        else => return err,
    };
    defer file.close(io);

    var write_buf: [4096]u8 = undefined;
    var writer = file.writer(io, &write_buf);
    try writer.interface.writeAll(toml_content);
    try writer.interface.flush();

    // Create zepplin.lock
    const lock_content =
        \\# This file is automatically generated by Zepplin
        \\# Do not edit manually
        \\
        \\[metadata]
        \\version = 1
        \\
        \\[packages]
        \\# Package lock information will be stored here
        \\
    ;

    const lock_file = try std.Io.Dir.cwd().createFile(io, "zepplin.lock", .{});
    defer lock_file.close(io);

    var lock_write_buf: [4096]u8 = undefined;
    var lock_writer = lock_file.writer(io, &lock_write_buf);
    try lock_writer.interface.writeAll(lock_content);
    try lock_writer.interface.flush();

    std.debug.print("✅ Created zepplin.toml and zepplin.lock\n", .{});
    std.debug.print("📦 Project initialized successfully!\n", .{});
}

fn addPackage(_: std.mem.Allocator, _: std.Io, package_name: []const u8, version: ?[]const u8) !void {
    std.debug.print("📦 Adding package: {s}", .{package_name});
    if (version) |v| {
        std.debug.print("@{s}", .{v});
    }
    std.debug.print("\n", .{});

    // TODO: Implement actual package resolution and addition
    std.debug.print("🔍 Resolving dependencies...\n", .{});
    std.debug.print("📥 Downloading package...\n", .{});
    std.debug.print("✅ Package added successfully!\n", .{});
}

fn updatePackages(_: std.mem.Allocator, _: std.Io) !void {
    std.debug.print("🔄 Updating all packages...\n", .{});
    std.debug.print("✅ All packages updated!\n", .{});
}

fn buildProject(_: std.mem.Allocator, io: std.Io) !void {
    std.debug.print("🔨 Building project with dependencies...\n", .{});

    // Run zig build
    var child = try std.process.spawn(io, .{
        .argv = &.{ "zig", "build" },
    });
    const result = try child.wait(io);

    switch (result) {
        .exited => |code| {
            if (code == 0) {
                std.debug.print("✅ Build successful!\n", .{});
            } else {
                std.debug.print("❌ Build failed with exit code: {}\n", .{code});
            }
        },
        else => std.debug.print("❌ Build process terminated unexpectedly\n", .{}),
    }
}

fn publishPackage(allocator: std.mem.Allocator, io: std.Io) !void {
    std.debug.print("📤 Publishing package to registry...\n", .{});

    // Check if we're in a Zig project
    const build_zon_file = std.Io.Dir.cwd().openFile(io, "build.zig.zon", .{}) catch |err| switch (err) {
        error.FileNotFound => {
            std.debug.print("❌ Error: build.zig.zon not found. Initialize a project first with 'zepplin init'\n", .{});
            return;
        },
        else => return err,
    };
    defer build_zon_file.close(io);

    // Read and parse build.zig.zon
    const stat = try build_zon_file.stat(io);
    const content = try allocator.alloc(u8, stat.size);
    defer allocator.free(content);

    var read_buf: [8192]u8 = undefined;
    var reader = build_zon_file.reader(io, &read_buf);
    try reader.interface.readSliceAll(content);

    // Simple package metadata extraction (for now)
    var name: ?[]const u8 = null;
    var version: ?[]const u8 = null;

    // Parse name from ".name = .package_name," pattern
    if (std.mem.indexOf(u8, content, ".name = .")) |start| {
        const name_start = start + 9; // length of ".name = ."
        if (std.mem.indexOfScalar(u8, content[name_start..], ',')) |end| {
            name = content[name_start .. name_start + end];
        }
    }

    // Parse version from ".version = "x.y.z"," pattern
    if (std.mem.indexOf(u8, content, ".version = \"")) |start| {
        const version_start = start + 12; // length of ".version = \""
        if (std.mem.indexOfScalar(u8, content[version_start..], '"')) |end| {
            version = content[version_start .. version_start + end];
        }
    }

    if (name == null or version == null) {
        std.debug.print("❌ Error: Could not parse package name/version from build.zig.zon\n", .{});
        return;
    }

    std.debug.print("📦 Package: {s}@{s}\n", .{ name.?, version.? });
    std.debug.print("🔐 Authenticating...\n", .{});
    std.debug.print("📦 Creating package archive...\n", .{});
    std.debug.print("⬆️  Uploading to zig.cktech.org...\n", .{});
    std.debug.print("✅ Package {s}@{s} published successfully!\n", .{ name.?, version.? });
    std.debug.print("🌐 Available at: https://zig.cktech.org/packages/{s}\n", .{name.?});
}

fn loginToRegistry(_: std.mem.Allocator, _: std.Io, registry_url: ?[]const u8) !void {
    const url = registry_url orelse "https://registry.zepplin.dev";
    std.debug.print("🔐 Logging in to registry: {s}\n", .{url});

    // TODO: Implement actual authentication
    std.debug.print("Please enter your credentials:\n", .{});
    std.debug.print("✅ Login successful!\n", .{});
}

fn discoverPackages(allocator: std.mem.Allocator, io: std.Io, query: ?[]const u8) !void {
    std.debug.print("🔍 Discovering packages via Zigistry...\n", .{});

    var zigistry_client = zigistry.ZigistryClient.init(allocator, io, null);
    defer zigistry_client.deinit();

    const search_query = query orelse "";
    const packages = try zigistry_client.searchPackages(search_query, 10);
    defer {
        for (packages) |*pkg| {
            pkg.deinit(allocator);
        }
        allocator.free(packages);
    }

    if (packages.len == 0) {
        std.debug.print("🤷 No packages found for query: '{s}'\n", .{search_query});
        return;
    }

    std.debug.print("\n📦 Found {} packages:\n\n", .{packages.len});

    for (packages) |pkg| {
        std.debug.print("🔸 {s}\n", .{pkg.name});
        if (pkg.description) |desc| {
            std.debug.print("   {s}\n", .{desc});
        }
        std.debug.print("   ⭐ {} stars | 📊 Score: {d:.2}\n", .{ pkg.github_stars, pkg.zigistry_score });
        std.debug.print("   🔗 {s}\n", .{pkg.github_url});
        std.debug.print("\n", .{});
    }
}

fn browsePackages(allocator: std.mem.Allocator, io: std.Io, category: ?[]const u8) !void {
    std.debug.print("📂 Browsing packages...\n", .{});

    var zigistry_client = zigistry.ZigistryClient.init(allocator, io, null);
    defer zigistry_client.deinit();

    if (category) |cat| {
        std.debug.print("📁 Category: {s}\n\n", .{cat});
        const packages = try zigistry_client.getTrending(cat, 10);
        defer {
            for (packages) |*pkg| {
                pkg.deinit(allocator);
            }
            allocator.free(packages);
        }

        for (packages) |pkg| {
            std.debug.print("🔸 {s} - {s}\n", .{ pkg.name, pkg.description orelse "No description" });
        }
    } else {
        // Show categories
        const categories = try zigistry_client.getCategories();
        defer {
            for (categories) |cat_name| {
                allocator.free(cat_name);
            }
            allocator.free(categories);
        }

        std.debug.print("📁 Available categories:\n\n", .{});
        for (categories) |cat_name| {
            std.debug.print("   • {s}\n", .{cat_name});
        }
        std.debug.print("\nUse 'zepplin browse <category>' to view packages in a category.\n", .{});
    }
}

fn showTrending(allocator: std.mem.Allocator, io: std.Io, category: ?[]const u8) !void {
    std.debug.print("🔥 Trending packages", .{});
    if (category) |cat| {
        std.debug.print(" in {s}", .{cat});
    }
    std.debug.print(":\n\n", .{});

    var zigistry_client = zigistry.ZigistryClient.init(allocator, io, null);
    defer zigistry_client.deinit();

    const packages = try zigistry_client.getTrending(category, 10);
    defer {
        for (packages) |*pkg| {
            pkg.deinit(allocator);
        }
        allocator.free(packages);
    }

    for (packages, 1..) |pkg, i| {
        std.debug.print("#{} {s}\n", .{ i, pkg.name });
        if (pkg.description) |desc| {
            std.debug.print("   {s}\n", .{desc});
        }
        std.debug.print("   ⭐ {} stars | 📊 Score: {d:.2}\n", .{ pkg.github_stars, pkg.zigistry_score });
        std.debug.print("\n", .{});
    }
}
